### ISSUE TITLE
Lab5 missing

### ISSUE THREAD

**Issue by godwillmonthe** [Kenneth-29/IS#3]
Mr ga ke bone folder ya lab5, o dirile jang yanong😶😂😂

**Comment by Kenneth-29** [comment]
Ke dirile ka bomo ke itse gore otloo e senka😂

**Comment by godwillmonthe** [comment]
Themona, e pushe hoo
________________________________

**Comment by Kenneth-29** [comment]
Mme kana e motlhofo...nna i lost it after resetting my pc
